### ISSUE TITLE
Wrong chown

### ISSUE THREAD

**Issue by MiteshShah** [kishorsd/myscript#5]
Why did you change ownership to $HOSTNAME?
ref: https://github.com/kishorsd/myscript/blob/master/myscript_rtcamp.sh#L52

**Comment by MiteshShah** [comment]
Why did you again chown to root?
Ref: https://github.com/kishorsd/myscript/blob/master/myscript_rtcamp.sh#L72

**Comment by kishorsd** [comment]
I was refering one tutorial. In that they said that, We need to grant ownership of the directory to the right user, instead of just keeping it on the root system. So i did chown to $HOSTNAME. But during testing I realised that directories should have root permision. So I chown with root and I forget to remove chown of $HOSTNAME.
